name: Build and Upload PostgreSQL

on:
  workflow_dispatch:
    inputs:
      version:
        description: "PostgreSQL major version (10, 12, 14, 16)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os_arch:
          - { os: linux, arch: amd64 }
          - { os: linux, arch: arm64 }
          - { os: windows, arch: amd64 }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user (for tagging)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate tag and create release
        if: matrix.os_arch.os == 'linux' && matrix.os_arch.arch == 'amd64'
        run: |
          git tag -f postgresql-v${{ inputs.version }}
          git push origin postgresql-v${{ inputs.version }} --force

      - name: Download or Build PostgreSQL (Linux)
        if: startsWith(matrix.os_arch.os, 'linux')
        shell: bash
        run: |
          chmod +x ./scripts/download-postgresql-linux.sh
          ./scripts/download-postgresql-linux.sh "${{ inputs.version }}" "${{ matrix.os_arch.arch }}"

          # Rename to standard format
          mv postgresql-linux-amd64/postgresql-*.tar.gz postgresql-${{ inputs.version }}-linux-amd64.tar.gz || true
          mv postgresql-${{ inputs.version }}-linux-arm64.tar.gz postgresql-${{ inputs.version }}-linux-arm64.tar.gz || true

      - name: Download PostgreSQL (Windows)
        if: matrix.os_arch.os == 'windows'
        shell: bash
        run: |
          chmod +x ./scripts/download-postgresql-windows.sh
          ./scripts/download-postgresql-windows.sh "${{ inputs.version }}"

          # Rename to standard format
          mv postgresql-windows-x64/postgresql-*.exe postgresql-${{ inputs.version }}-windows-amd64.zip || true
          zip postgresql-${{ inputs.version }}-windows-amd64.zip postgresql-${{ inputs.version }}-windows-amd64.exe || true

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: postgresql-v${{ inputs.version }}
          name: PostgreSQL ${{ inputs.version }} binaries
          files: |
            postgresql-${{ inputs.version }}-linux-amd64.tar.gz
            postgresql-${{ inputs.version }}-linux-arm64.tar.gz
            postgresql-${{ inputs.version }}-windows-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
